{% set name = "coredis" %}
{% set version = "4.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/coredis-{{ version }}.tar.gz
  sha256: 04e9976e71a42004dfe19a862c648b4047bf813e15184cddfd3cb37eb704b83f

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - mypy ==1.7.1
    - packaging >=21,<24
    - setuptools
    - types-deprecated
    - versioneer
    - pip
  run:
    - python
    - async-timeout <5,>4
    - deprecated >=1.2
    - typing-extensions >=4.3
    - packaging >=21,<25
    - pympler >1,<2
    - wrapt >=1.1.0,<2

test:
  imports:
    - coredis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alisaifee/coredis
  summary: Python async client for Redis key-value store
  dev_url: https://github.com/alisaifee/coredis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
